version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
    ports:
      - 9200:9200
    networks:
      es_net:
        aliases:
          - elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  logstash:
    image: onap/clamp-dashboard-logstash:latest
    build:
      context: ../../../src/main/docker/logstash
      dockerfile: Dockerfile.logstash
    volumes:
      - ../../../src/main/docker/logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash-input:/log-input
    depends_on:
      - elasticsearch
    networks:
      es_net:
    environment:
      - dmaap_base_url=http://dmaapmocker:3904/
      - dmaap_user=user
      - dmaap_password=password
      - dmaap_consumer_group=clampdashboard
      - dmaap_consumer_id=clampdashboard
      - event_topic=DCAE-CL-EVENT
      - notification_topic=POLICY-CL-MGT
      - request_topic=APPC-CL
      - elasticsearch_base_url=elasticsearch

  kibana:
    image: onap/clamp-dashboard-kibana:latest
    build:
      context: ../../../src/main/docker/kibana
      dockerfile: Dockerfile.kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - ../../../src/main/docker/kibana/saved-objects/:/saved-objects/
    networks:
      es_net:

networks:
  es_net:
