#
# ===========LICENSE_START====================================================
#  Copyright (C) 2022-2024 Nordix Foundation.
#  Modifications Copyright 2025 Deutsche Telekom
# ============================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=====================================================
#

# global config
global:
  scrape_interval: 60s
  evaluation_interval: 60s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# scrape config
scrape_configs:

- job_name: "api-metrics"
  metrics_path: /policy/api/v1/metrics
  static_configs:
  - targets: ["policy-api:6969"]
  basic_auth:
    username: "policyadmin"
    password: "zb!XztG34"

- job_name: "pap-metrics"
  metrics_path: /policy/pap/v1/metrics
  static_configs:
  - targets: ["policy-pap:6969"]
  basic_auth:
    username: "policyadmin"
    password: "zb!XztG34"

- job_name: "apex-pdp-metrics"
  static_configs:
  - targets:
    - "policy-apex-pdp:6969"
  basic_auth:
    username: "policyadmin"
    password: "zb!XztG34"

- job_name: "acm-metrics"
  metrics_path: "/onap/policy/clamp/acm/prometheus"
  static_configs:
  - targets:
    - "policy-clamp-runtime-acm:6969"
  basic_auth:
    username: "runtimeUser"
    password: "zb!XztG34"
