
participant:
  name: ControlLoopParticipantDcae
  clampClientEndPoints:
    status: /restservices/clds/v2/loop/getstatus/
    create: /restservices/clds/v2/loop/create/%s?templateName=%s
    deploy: /restservices/clds/v2/loop/deploy/
    stop: /restservices/clds/v2/loop/stop/
    delete: /restservices/clds/v2/loop/delete/
    undeploy: /restservices/clds/v2/loop/undeploy/
  clampClientParameters:
    clientName: Clamp
    hostname: 0.0.0.0
    port: 8443
    userName: admin
    password: password
    https: true
    aaf: false
  consulClientEndPoints:
    deploy: "/v1/kv/dcae-pmsh:"
  consulClientParameters:
    clientName: Consul
    hostname: consul
    port: 31321
    userName: admin
    password: password
    https: false
    aaf: false
  intermediaryParameters:
    name: Participant parameters
    reportingTimeInterval: 120000
    description: Participant Description
    participantId:
      name: DCAEParticipant0
      version: 1.0.0
    participantType:
      name: org.onap.dcae.controlloop.DCAEMicroserviceControlLoopParticipant
      version: 2.3.4
    clampControlLoopTopics:
      topicSources[0]:
        topic: POLICY-CLRUNTIME-PARTICIPANT
        servers[0]: ${topicServer:message-router}
        topicCommInfrastructure: dmaap
        fetchTimeout: 15000
      topicSinks[0]:
        topic: POLICY-CLRUNTIME-PARTICIPANT
        servers[0]: ${topicServer:message-router}
        topicCommInfrastructure: dmaap
      topicSinks[1]:
        topic: POLICY-NOTIFICATION
        servers[0]: ${topicServer:message-router}
        topicCommInfrastructure: dmaap
  checkCount: 10
  jsonBodyConsulPath: src/main/resources/parameters/consul.json
