spring:
  security:
    user:
      name: healthcheck
      password: zb!XztG34

participant:
  pdpGroup: defaultGroup
  pdpType: apex
  policyApiParameters:
    clientName: api
    hostname: policy-api
    port: 6969
    userName: healthcheck
    password: zb!XztG34
    https: true
    allowSelfSignedCerts: true
  policyPapParameters:
    clientName: pap
    hostname: policy-pap
    port: 6969
    userName: healthcheck
    password: zb!XztG34
    https: true
    allowSelfSignedCerts: true
  intermediaryParameters:
    reportingTimeIntervalMs: 120000
    description: Participant Description
    participantId:
      name: org.onap.PM_Policy
      version: 1.0.0
    participantType:
      name: org.onap.policy.controlloop.PolicyControlLoopParticipant
      version: 2.3.1
    clampControlLoopTopics:
      topicSources:
        -
          topic: POLICY-CLRUNTIME-PARTICIPANT
          servers:
            - ${topicServer:localhost}
          topicCommInfrastructure: dmaap
          fetchTimeout: 15000
      topicSinks:
        -
          topic: POLICY-CLRUNTIME-PARTICIPANT
          servers:
            - ${topicServer:localhost}
          topicCommInfrastructure: dmaap
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
server:
  port: 8085
  servlet:
    context-path: /onap/policyparticipant
